name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'
        cache: gradle

    - name: Gradle
      run: gradle wrapper --gradle-version 5.4.1

    - name: Grant execute permission for gradlew
      run: chmod 777 gradlew
    - name: Build with Gradle
      run: ./gradlew build
